name: las-ci
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        shell: powershell
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module Pester -MinimumVersion 5.5.0 -Force -Scope CurrentUser
      - name: Run Pester
        shell: powershell
        run: Invoke-Pester -CI
